//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentMaster()
        {
            this.AppointmentDetails = new HashSet<AppointmentDetail>();
            this.AppointmentProjects = new HashSet<AppointmentProject>();
            this.OrderRequestDetails = new HashSet<OrderRequestDetail>();
            this.SalaryDetails = new HashSet<SalaryDetail>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string MeetingID { get; set; }
        public string CandidateID { get; set; }
        public System.DateTime DOB { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public decimal BasicSalary { get; set; }
        public string PermanentAddress { get; set; }
        public string CommunicationAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSC_Code { get; set; }
        public string OutSourcingCompany { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
        public virtual OutSourcingDesignation OutSourcingDesignation { get; set; }
        public virtual OutsourcingEmployeeDetail OutsourcingEmployeeDetail { get; set; }
        public virtual OutsourcingMeeting OutsourcingMeeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentProject> AppointmentProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequestDetail> OrderRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryDetail> SalaryDetails { get; set; }
    }
}
