//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequestDetail
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int OrderID { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<System.DateTime> OrderRequestDate { get; set; }
        public Nullable<System.DateTime> OrderReceiveDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AppointmentMaster AppointmentMaster { get; set; }
    }
}
