//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_Section
    {
        public string SecId { get; set; }
        public string SectionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
