//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItemMaster
    {
        public string ListName { get; set; }
        public string ListItemValue { get; set; }
        public string ListItemText { get; set; }
        public string ListGroup { get; set; }
    }
}
