//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourcingMeeting
    {
        public OutsourcingMeeting()
        {
            this.AppointmentDetails = new HashSet<AppointmentDetail>();
            this.AppointmentMasters = new HashSet<AppointmentMaster>();
            this.AppointmentProjects = new HashSet<AppointmentProject>();
        }
    
        public string MeetingID { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public string CandidateID { get; set; }
        public string CandidateName { get; set; }
        public System.DateTime DOB { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string Qualification { get; set; }
        public bool IITMExperience { get; set; }
        public Nullable<decimal> IIT_Experience { get; set; }
        public Nullable<decimal> NONIIT_Experience { get; set; }
        public Nullable<decimal> Total_Experience { get; set; }
        public string ProjectType { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectTitle { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string SponsoredAgency { get; set; }
        public string PICode { get; set; }
        public string PIName { get; set; }
        public Nullable<System.DateTime> ProjectCloseDate { get; set; }
        public string Section { get; set; }
        public string OutSourcingCompany { get; set; }
        public System.DateTime RequestFromDate { get; set; }
        public System.DateTime RequestToDate { get; set; }
        public Nullable<int> DurationInMonth { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public decimal GrossSalary { get; set; }
        public decimal CostToProject { get; set; }
        public string CommitmentNo { get; set; }
        public string StatusOfRequest { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
        public virtual ICollection<AppointmentMaster> AppointmentMasters { get; set; }
        public virtual ICollection<AppointmentProject> AppointmentProjects { get; set; }
        public virtual OutsourcingOffer OutsourcingOffer { get; set; }
        public virtual OutSourcingDesignation OutSourcingDesignation { get; set; }
        public virtual OutsourcingEmployeeDetail OutsourcingEmployeeDetails { get; set; }
    }
}
