//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsourcingOffer
    {
        public string MeetingID { get; set; }
        public int RequestID { get; set; }
        public System.DateTime OfferRequestDate { get; set; }
        public Nullable<System.DateTime> OfferReceivedDate { get; set; }
        public string OfferStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string JoiningReportApprovedBy { get; set; }
        public Nullable<System.DateTime> JoiningReportDate { get; set; }
        public string ApprovalChannel { get; set; }
    
        public virtual OutsourcingMeeting OutsourcingMeeting { get; set; }
    }
}
