//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outsourcing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalTax
    {
        public System.DateTime EffectiveDate { get; set; }
        public decimal PayRangeFrom { get; set; }
        public decimal PayRangeTo { get; set; }
        public decimal ProfessionalTax1 { get; set; }
    }
}
